---
include:
  - template: 'Security/License-Scanning.gitlab-ci.yml'
  - template: 'SAST.gitlab-ci.yml'
  - template: 'Dependency-Scanning.gitlab-ci.yml'
  - template: 'Code-Quality.gitlab-ci.yml'

variables:
  MAVEN_CLI_OPTS: '-Dgpg.skip=true -Dmaven.test.skip=true'

stages: [build, test, deploy]

cache:
  paths:
    - "$HOME/.m2/"

.build:
  stage: build
  script:
    - "mvn clean package -Dmaven.test.skip=true -Dgpg.skip=true"
  artifacts:
    paths:
      - "target/*.jar"

.test:
  stage: test
  script:
    - "mvn test -Dgpg.skip=true -Dhetzner.token=${HETZNER_TOKEN}"

build:jdk8:
  image: maven:3-jdk-8
  extends: [".build"]

build:jdk16:
  image: maven:3-openjdk-16
  extends: [".build"]

test:jdk8:
  image: maven:3-jdk-8
  extends: [".test"]
  needs:
    - job: build:jdk8

pages:
  image: maven:3-jdk-8
  stage: deploy
  script:
    - "mkdir .public"
    - "mvn javadoc:javadoc"
    - "cp -R target/site/apidocs/* .public/"
    - "mv .public public"
  artifacts:
    paths:
      - public
  only:
    - master
